name: deploy
env:
  APP_SERVICE_NAME: 'marcavans' # Set the name of your app service here
on:
    # 👇 Trigger the workflow on a push to the main branch. Remove if you would only to deploy manually
    push:
        branches: main

    # 👇 Allows you to run this workflow manually (for any branch) from the Actions tab.
    workflow_dispatch:

jobs:
    # 👇 Call the build workflow to create the artifacts to deploy.
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit # Pass secrets to the build workflow, if necessary.

    deploy:
         # Only run this deploy job after the build-and-test job completes successfully.
        needs: build
        runs-on: ubuntu-latest
        environment: production # Used for environment-specific variables, secrets, and approvals.
        steps:
          - name: Download api
            uses: actions/download-artifact@v4
            with:
                name: deployme-api
                path: ./api
         
          - name: Download migrations
            uses: actions/download-artifact@v4
            with:
                name: deployme-migrations
                path: ./migrations
            
            # Step to execute the ef migrations
          - name: Execute EF migrations
            run: |
                  chmod +x ./migrations/migrations.exe
                  ./migrations/migrations.exe --connection "${{ secrets.AZURE_SQL_DATABASE_OWNER }}"

          - uses: azure/login@v1
            with:
                creds: '${{ secrets.AZURE_CREDENTIALS }}'

            # Step to deploy the code to Azure Web App
          - name: 'Deploy to Azure Web App'
            uses: azure/webapps-deploy@v2
            with:
                app-name: '${{env.APP_SERVICE_NAME}}' 
                package: ./api 

          - uses: azure/appservice-settings@v1
            with:
                app-name: '${{env.APP_SERVICE_NAME}}'
                app-settings-json: '[{ "name": "ConnectionStringAzureSQL", "value": "${{ secrets.AZURE_SQL_DATABASE_APPLICATION_USER }}"}]' 

                